// Fill out your copyright notice in the Description page of Project Settings.


#include "PlaceholderCharacter.h"

// Sets default values
APlaceholderCharacter::APlaceholderCharacter()
{
 	// Set this character to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

}

// Called when the game starts or when spawned
void APlaceholderCharacter::BeginPlay()
{
	Super::BeginPlay();
	
}

// Called every frame
void APlaceholderCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

}

// Called to bind functionality to input
void APlaceholderCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

}

